
public class intro extends javax.swing.JFrame {

    /**
     * Creates new form intro
    fourth fourth; */
    data fourth;
    gameGrid second;
    
    int count =1;
    
    public intro() {
        fourth = new data ();
        second = new gameGrid(0,0,0,0,0);
        initComponents();
    }
    
    public intro(data data1) {
        fourth = data1 ;
        initComponents();
    }
    public intro(gameGrid gameGrid1) {
       
        second = gameGrid1 ;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        introText = new javax.swing.JTextArea();
        nextButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        introText.setColumns(20);
        introText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        introText.setRows(5);
        introText.setText("Welcome to the Game of Life.\n\nThe Game of Life is intended to model life in a society of organisms.\nConsider a rectangular array of cells, each of which may contain an organism.\nEach cell will have 8 neighbours.\n\nIn each generation births and deaths occur according to the following rules:\n\t1. An organism is born in an empty cell that has exactly 3 nieghbours\n\t2. An organism will die from isolation if it has fewer than 2 neighbours\n\t3. An organism will di from overcrouwding if it has more than 3 nieghbours.");
        jScrollPane2.setViewportView(introText);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nextButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        
        //Creating if statements to run different code under different circumdtances
        if(count==1){
            //Setting the gui visibility to false so the text will no longer continue to appear
            this.setVisible(false);

            fourth.outputSet("Choose a number of rows");

            //Setiing the fourth gui visibility to ture so it will appear on button press
            fourth.setVisible(true);    
        }else if (count>=2 && count-2<second.genValue){
            second.nextGen();
            second.print();
            
        }else if (count-2>second.genValue){
            introSet("End of program");
            
        }else if(count-1>second.genValue){
            this.setVisible(false);
            
        }
        
        count++;
        
        
    }//GEN-LAST:event_nextButtonActionPerformed

    //Creating a methid
    public void introSet (String intro){
        
        introText.setText(intro);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea introText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
